import Foundation
import OCGUI

class ReversiAppOld : OCApp {
    // Buttons used in the gui.
    var tileAA: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileAB: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileAC: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileAD: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileAE: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileAF: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileAG: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileAH: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileBA: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileBB: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileBC: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileBD: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileBE: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileBF: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileBG: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileBH: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileCA: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileCB: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileCC: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileCD: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileCE: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileCF: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileCG: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileCH: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileDA: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileDB: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileDC: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileDD: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileDE: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileDF: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileDG: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileDH: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileEA: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileEB: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileEC: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileED: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileEE: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileEF: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileEG: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileEH: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileFA: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileFB: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileFC: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileFD: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileFE: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileFF: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileFG: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileFH: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileGA: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileGB: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileGC: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileGD: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileGE: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileGF: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileGG: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileGH: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileHA: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileHB: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileHC: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileHD: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileHE: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileHF: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileHG: OCImageView = OCImageView(filename: "images/SquareOutline.png")
    var tileHH: OCImageView = OCImageView(filename: "images/SquareOutline.png")



/// Event function for when the "next" button is pressed.
    func tilePressed(tile: OCControlClickable) {
        // If a flash card has not been shown previous to this, will assume the user is starting the flashcard app.
        tileAA.filename = "images/SquareOutline.png"
        }
    
    override open func main(app: OCAppDelegate) -> OCControl {
        self.tileAA.onClick(self.tilePressed)
        self.tileAB.onClick(self.tilePressed)
        self.tileAC.onClick(self.tilePressed)
        self.tileAD.onClick(self.tilePressed)
        self.tileAE.onClick(self.tilePressed)
        self.tileAF.onClick(self.tilePressed)
        self.tileAG.onClick(self.tilePressed)
        self.tileAH.onClick(self.tilePressed)
        self.tileBA.onClick(self.tilePressed)
        self.tileBB.onClick(self.tilePressed)
        self.tileBC.onClick(self.tilePressed)
        self.tileBB.onClick(self.tilePressed)
        self.tileBD.onClick(self.tilePressed)
        self.tileBE.onClick(self.tilePressed)
        self.tileBF.onClick(self.tilePressed)
        self.tileBG.onClick(self.tilePressed)
        self.tileBH.onClick(self.tilePressed)
        self.tileCA.onClick(self.tilePressed)
        self.tileCB.onClick(self.tilePressed)
        self.tileCC.onClick(self.tilePressed)
        self.tileCD.onClick(self.tilePressed)
        self.tileCE.onClick(self.tilePressed)
        self.tileCF.onClick(self.tilePressed)
        self.tileCG.onClick(self.tilePressed)
        self.tileCH.onClick(self.tilePressed)
        self.tileDA.onClick(self.tilePressed)
        self.tileDB.onClick(self.tilePressed)
        self.tileDC.onClick(self.tilePressed)
        self.tileDD.onClick(self.tilePressed)
        self.tileDE.onClick(self.tilePressed)
        self.tileDF.onClick(self.tilePressed)
        self.tileDG.onClick(self.tilePressed)
        self.tileDH.onClick(self.tilePressed)
        self.tileEA.onClick(self.tilePressed)
        self.tileEB.onClick(self.tilePressed)
        self.tileEC.onClick(self.tilePressed)
        self.tileED.onClick(self.tilePressed)
        self.tileEE.onClick(self.tilePressed)
        self.tileEF.onClick(self.tilePressed)
        self.tileEG.onClick(self.tilePressed)
        self.tileEH.onClick(self.tilePressed)
        self.tileFA.onClick(self.tilePressed)
        self.tileFB.onClick(self.tilePressed)
        self.tileFC.onClick(self.tilePressed)
        self.tileFD.onClick(self.tilePressed)
        self.tileFE.onClick(self.tilePressed)
        self.tileFF.onClick(self.tilePressed)
        self.tileFG.onClick(self.tilePressed)
        self.tileFH.onClick(self.tilePressed)
        self.tileGA.onClick(self.tilePressed)
        self.tileGB.onClick(self.tilePressed)
        self.tileGC.onClick(self.tilePressed)
        self.tileGD.onClick(self.tilePressed)
        self.tileGE.onClick(self.tilePressed)
        self.tileGF.onClick(self.tilePressed)
        self.tileGG.onClick(self.tilePressed)
        self.tileGH.onClick(self.tilePressed)
        self.tileHA.onClick(self.tilePressed)
        self.tileHB.onClick(self.tilePressed)
        self.tileHC.onClick(self.tilePressed)
        self.tileHD.onClick(self.tilePressed)
        self.tileHE.onClick(self.tilePressed)
        self.tileHF.onClick(self.tilePressed)
        self.tileHG.onClick(self.tilePressed)
        self.tileHH.onClick(self.tilePressed)


        let TileButtonsRowOne = OCHBox(controls: [tileAA, tileAB, tileAC, tileAD, tileAE, tileAF, tileAG, tileAH])
        let TileButtonsRowTwo = OCHBox(controls: [tileBA, tileBB, tileBC, tileBD, tileBE, tileBF, tileBG, tileBH])
        let TileButtonsRowThree = OCHBox(controls: [tileCA, tileCB, tileCC, tileCD, tileCE, tileCF, tileCG, tileCH])
        let TileButtonsRowFour = OCHBox(controls: [tileDA, tileDB, tileDC, tileDD, tileDE, tileDF, tileDG, tileDH])
        let TileButtonsRowFive = OCHBox(controls: [tileEA, tileEB, tileEC, tileED, tileEE, tileEF, tileEG, tileEH])
        let TileButtonsRowSix = OCHBox(controls: [tileFA, tileFB, tileFC, tileFD, tileFE, tileFF, tileFG, tileFH])
        let TileButtonsRowSeven = OCHBox(controls: [tileGA, tileGB, tileGC, tileGD, tileGE, tileGF, tileGG, tileGH])
        let TileButtonsRowEight = OCHBox(controls: [tileHA, tileHB, tileHC, tileHD, tileHE, tileHF, tileHG, tileHH])
        let Grid = OCVBox(controls: [TileButtonsRowOne, TileButtonsRowTwo, TileButtonsRowThree, TileButtonsRowFour, TileButtonsRowFive, TileButtonsRowSix, TileButtonsRowSeven, TileButtonsRowEight])

        return Grid
    }
}